---
title: Welcome to Olle Lindholm's portfolio!
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  blog:
    title: blog
    output: true
theme: jekyll-theme-cayman
Description: Feel free to bookmark this to keep an eye on my project updates.
